/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActingDriverRequest {
  'status' : BookingStatus,
  'serviceDate' : bigint,
  'requestId' : string,
  'serviceDetails' : string,
  'bookingDate' : bigint,
  'guest' : Principal,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface CabBooking {
  'status' : BookingStatus,
  'bookingId' : string,
  'dropoffLocation' : string,
  'cabType' : string,
  'bookingDate' : bigint,
  'guest' : Principal,
  'pickupTime' : bigint,
  'totalPrice' : bigint,
  'pickupLocation' : string,
}
export interface CabType {
  'name' : string,
  'pricePerTrip' : bigint,
  'imageUrl' : string,
  'capacity' : bigint,
}
export interface HotelBooking {
  'status' : BookingStatus,
  'depositAmount' : bigint,
  'bookingId' : string,
  'remainingAmount' : bigint,
  'checkInDate' : bigint,
  'bookingDate' : bigint,
  'guest' : Principal,
  'paymentPlan' : PaymentPlan,
  'checkOutDate' : bigint,
  'totalPrice' : bigint,
  'roomType' : string,
  'depositPercentage' : bigint,
}
export interface Inquiry {
  'status' : { 'new' : null } |
    { 'closed' : null } |
    { 'reviewed' : null },
  'contactInfo' : string,
  'customer' : Principal,
  'message' : string,
  'timestamp' : bigint,
  'inquiryId' : string,
}
export type PaymentPlan = { 'cod' : null } |
  { 'partialUpfront' : null } |
  { 'depositRequired' : null } |
  { 'fullUpfront' : null };
export interface PaymentRecord {
  'status' : { 'new' : null } |
    { 'verified' : null } |
    { 'rejected' : null },
  'customer' : Principal,
  'note' : string,
  'reference' : string,
  'paymentId' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface Product {
  'imageUrls' : Array<string>,
  'name' : string,
  'description' : string,
  'productId' : string,
  'category' : string,
  'price' : bigint,
}
export interface RoomType {
  'features' : Array<string>,
  'imageUrls' : Array<string>,
  'pricePerNight' : bigint,
  'name' : string,
}
export interface SalesOrder {
  'status' : BookingStatus,
  'deliveryAddress' : string,
  'remainingAmount' : bigint,
  'customer' : Principal,
  'orderDate' : bigint,
  'email' : string,
  'orderId' : string,
  'upfrontAmount' : bigint,
  'paymentPlan' : PaymentPlan,
  'contactNumber' : string,
  'products' : Array<Product>,
  'totalPrice' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookCab' : ActorMethod<[string, string, string, bigint], string>,
  'bookHotel' : ActorMethod<[string, bigint, bigint], string>,
  'cancelCallerSalesOrder' : ActorMethod<[string], undefined>,
  'createSalesOrder' : ActorMethod<
    [Array<Product>, string, string, string, bigint, PaymentPlan],
    string
  >,
  'getAllActingDriverRequests' : ActorMethod<[], Array<ActingDriverRequest>>,
  'getAllCabBookings' : ActorMethod<[], Array<CabBooking>>,
  'getAllHotelBookings' : ActorMethod<[], Array<HotelBooking>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'getAllSalesOrders' : ActorMethod<[], Array<SalesOrder>>,
  'getCabTypes' : ActorMethod<[], Array<CabType>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyActingDriverRequests' : ActorMethod<[], Array<ActingDriverRequest>>,
  'getMyCabBookings' : ActorMethod<[], Array<CabBooking>>,
  'getMyHotelBookings' : ActorMethod<[], Array<HotelBooking>>,
  'getMyInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getMyPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'getMySalesOrders' : ActorMethod<[], Array<SalesOrder>>,
  'getRoomTypes' : ActorMethod<[], Array<RoomType>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestActingDriver' : ActorMethod<[string, bigint], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitInquiry' : ActorMethod<[string, string], string>,
  'submitPayment' : ActorMethod<[string, string, bigint], string>,
  'updateActingDriverRequestStatus' : ActorMethod<
    [string, BookingStatus],
    undefined
  >,
  'updateCabBookingStatus' : ActorMethod<[string, BookingStatus], undefined>,
  'updateCallerSalesOrderDate' : ActorMethod<[string, bigint], undefined>,
  'updateHotelBookingStatus' : ActorMethod<[string, BookingStatus], undefined>,
  'updateInquiryStatus' : ActorMethod<
    [string, { 'new' : null } | { 'closed' : null } | { 'reviewed' : null }],
    undefined
  >,
  'updatePaymentStatus' : ActorMethod<
    [string, { 'new' : null } | { 'verified' : null } | { 'rejected' : null }],
    undefined
  >,
  'updateSalesOrderStatus' : ActorMethod<[string, BookingStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];