/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DateRange = IDL.Record({
  'checkIn' : IDL.Int,
  'checkOut' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Product = IDL.Record({
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'productId' : IDL.Text,
  'offerPrice' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const PaymentPlan = IDL.Variant({
  'cod' : IDL.Null,
  'partialUpfront' : IDL.Null,
  'depositRequired' : IDL.Null,
  'fullUpfront' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const ActingDriverRequest = IDL.Record({
  'status' : BookingStatus,
  'serviceDate' : IDL.Int,
  'vehicleType' : IDL.Text,
  'requestId' : IDL.Text,
  'serviceDetails' : IDL.Text,
  'bookingDate' : IDL.Int,
  'guest' : IDL.Principal,
});
export const CabBooking = IDL.Record({
  'status' : BookingStatus,
  'bookingId' : IDL.Text,
  'dropoffLocation' : IDL.Text,
  'cabType' : IDL.Text,
  'bookingDate' : IDL.Int,
  'guest' : IDL.Principal,
  'pickupTime' : IDL.Int,
  'totalPrice' : IDL.Nat,
  'pickupLocation' : IDL.Text,
});
export const HotelBooking = IDL.Record({
  'status' : BookingStatus,
  'depositAmount' : IDL.Nat,
  'bookingId' : IDL.Text,
  'remainingAmount' : IDL.Nat,
  'checkInDate' : IDL.Int,
  'bookingDate' : IDL.Int,
  'guest' : IDL.Principal,
  'paymentPlan' : PaymentPlan,
  'checkOutDate' : IDL.Int,
  'totalPrice' : IDL.Nat,
  'roomType' : IDL.Text,
  'depositPercentage' : IDL.Nat,
});
export const Inquiry = IDL.Record({
  'status' : IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Null,
    'reviewed' : IDL.Null,
  }),
  'contactInfo' : IDL.Text,
  'customer' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'inquiryId' : IDL.Text,
});
export const PaymentRecord = IDL.Record({
  'status' : IDL.Variant({
    'new' : IDL.Null,
    'verified' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'customer' : IDL.Principal,
  'note' : IDL.Text,
  'reference' : IDL.Text,
  'paymentId' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const SalesOrder = IDL.Record({
  'status' : BookingStatus,
  'deliveryAddress' : IDL.Text,
  'remainingAmount' : IDL.Nat,
  'customer' : IDL.Principal,
  'orderDate' : IDL.Int,
  'email' : IDL.Text,
  'orderId' : IDL.Text,
  'upfrontAmount' : IDL.Nat,
  'paymentPlan' : PaymentPlan,
  'contactNumber' : IDL.Text,
  'products' : IDL.Vec(Product),
  'totalPrice' : IDL.Nat,
});
export const CabAvailability = IDL.Record({
  'availableCount' : IDL.Nat,
  'cabType' : IDL.Text,
});
export const CabType = IDL.Record({
  'name' : IDL.Text,
  'pricePerTrip' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'offerPrice' : IDL.Nat,
  'capacity' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const RoomType = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'imageUrls' : IDL.Vec(IDL.Text),
  'pricePerNight' : IDL.Nat,
  'name' : IDL.Text,
  'offerPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRoomAvailability' : IDL.Func([IDL.Text, IDL.Vec(DateRange)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookCab' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Int], [IDL.Text], []),
  'bookHotel' : IDL.Func([IDL.Text, IDL.Int, IDL.Int], [IDL.Text], []),
  'cancelCallerSalesOrder' : IDL.Func([IDL.Text], [], []),
  'createSalesOrder' : IDL.Func(
      [IDL.Vec(Product), IDL.Text, IDL.Text, IDL.Text, IDL.Nat, PaymentPlan],
      [IDL.Text],
      [],
    ),
  'getAllActingDriverRequests' : IDL.Func(
      [],
      [IDL.Vec(ActingDriverRequest)],
      ['query'],
    ),
  'getAllCabBookings' : IDL.Func([], [IDL.Vec(CabBooking)], ['query']),
  'getAllHotelBookings' : IDL.Func([], [IDL.Vec(HotelBooking)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getAllRoomAvailability' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(DateRange)))],
      ['query'],
    ),
  'getAllSalesOrders' : IDL.Func([], [IDL.Vec(SalesOrder)], ['query']),
  'getCabAvailability' : IDL.Func([], [IDL.Vec(CabAvailability)], ['query']),
  'getCabTypes' : IDL.Func([], [IDL.Vec(CabType)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyActingDriverRequests' : IDL.Func(
      [],
      [IDL.Vec(ActingDriverRequest)],
      ['query'],
    ),
  'getMyCabBookings' : IDL.Func([], [IDL.Vec(CabBooking)], ['query']),
  'getMyHotelBookings' : IDL.Func([], [IDL.Vec(HotelBooking)], ['query']),
  'getMyInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getMySalesOrders' : IDL.Func([], [IDL.Vec(SalesOrder)], ['query']),
  'getRoomAvailability' : IDL.Func([IDL.Text], [IDL.Vec(DateRange)], ['query']),
  'getRoomTypes' : IDL.Func([], [IDL.Vec(RoomType)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestActingDriver' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCabAvailability' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'submitPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
  'updateActingDriverRequestStatus' : IDL.Func(
      [IDL.Text, BookingStatus],
      [],
      [],
    ),
  'updateCabBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
  'updateCallerSalesOrderDate' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'updateHotelBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
  'updateInquiryStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'new' : IDL.Null,
          'closed' : IDL.Null,
          'reviewed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updatePaymentStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'new' : IDL.Null,
          'verified' : IDL.Null,
          'rejected' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateSalesOrderStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DateRange = IDL.Record({ 'checkIn' : IDL.Int, 'checkOut' : IDL.Int });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Product = IDL.Record({
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'productId' : IDL.Text,
    'offerPrice' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const PaymentPlan = IDL.Variant({
    'cod' : IDL.Null,
    'partialUpfront' : IDL.Null,
    'depositRequired' : IDL.Null,
    'fullUpfront' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const ActingDriverRequest = IDL.Record({
    'status' : BookingStatus,
    'serviceDate' : IDL.Int,
    'vehicleType' : IDL.Text,
    'requestId' : IDL.Text,
    'serviceDetails' : IDL.Text,
    'bookingDate' : IDL.Int,
    'guest' : IDL.Principal,
  });
  const CabBooking = IDL.Record({
    'status' : BookingStatus,
    'bookingId' : IDL.Text,
    'dropoffLocation' : IDL.Text,
    'cabType' : IDL.Text,
    'bookingDate' : IDL.Int,
    'guest' : IDL.Principal,
    'pickupTime' : IDL.Int,
    'totalPrice' : IDL.Nat,
    'pickupLocation' : IDL.Text,
  });
  const HotelBooking = IDL.Record({
    'status' : BookingStatus,
    'depositAmount' : IDL.Nat,
    'bookingId' : IDL.Text,
    'remainingAmount' : IDL.Nat,
    'checkInDate' : IDL.Int,
    'bookingDate' : IDL.Int,
    'guest' : IDL.Principal,
    'paymentPlan' : PaymentPlan,
    'checkOutDate' : IDL.Int,
    'totalPrice' : IDL.Nat,
    'roomType' : IDL.Text,
    'depositPercentage' : IDL.Nat,
  });
  const Inquiry = IDL.Record({
    'status' : IDL.Variant({
      'new' : IDL.Null,
      'closed' : IDL.Null,
      'reviewed' : IDL.Null,
    }),
    'contactInfo' : IDL.Text,
    'customer' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'inquiryId' : IDL.Text,
  });
  const PaymentRecord = IDL.Record({
    'status' : IDL.Variant({
      'new' : IDL.Null,
      'verified' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'customer' : IDL.Principal,
    'note' : IDL.Text,
    'reference' : IDL.Text,
    'paymentId' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const SalesOrder = IDL.Record({
    'status' : BookingStatus,
    'deliveryAddress' : IDL.Text,
    'remainingAmount' : IDL.Nat,
    'customer' : IDL.Principal,
    'orderDate' : IDL.Int,
    'email' : IDL.Text,
    'orderId' : IDL.Text,
    'upfrontAmount' : IDL.Nat,
    'paymentPlan' : PaymentPlan,
    'contactNumber' : IDL.Text,
    'products' : IDL.Vec(Product),
    'totalPrice' : IDL.Nat,
  });
  const CabAvailability = IDL.Record({
    'availableCount' : IDL.Nat,
    'cabType' : IDL.Text,
  });
  const CabType = IDL.Record({
    'name' : IDL.Text,
    'pricePerTrip' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'offerPrice' : IDL.Nat,
    'capacity' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RoomType = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'imageUrls' : IDL.Vec(IDL.Text),
    'pricePerNight' : IDL.Nat,
    'name' : IDL.Text,
    'offerPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRoomAvailability' : IDL.Func([IDL.Text, IDL.Vec(DateRange)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookCab' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Text],
        [],
      ),
    'bookHotel' : IDL.Func([IDL.Text, IDL.Int, IDL.Int], [IDL.Text], []),
    'cancelCallerSalesOrder' : IDL.Func([IDL.Text], [], []),
    'createSalesOrder' : IDL.Func(
        [IDL.Vec(Product), IDL.Text, IDL.Text, IDL.Text, IDL.Nat, PaymentPlan],
        [IDL.Text],
        [],
      ),
    'getAllActingDriverRequests' : IDL.Func(
        [],
        [IDL.Vec(ActingDriverRequest)],
        ['query'],
      ),
    'getAllCabBookings' : IDL.Func([], [IDL.Vec(CabBooking)], ['query']),
    'getAllHotelBookings' : IDL.Func([], [IDL.Vec(HotelBooking)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getAllRoomAvailability' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(DateRange)))],
        ['query'],
      ),
    'getAllSalesOrders' : IDL.Func([], [IDL.Vec(SalesOrder)], ['query']),
    'getCabAvailability' : IDL.Func([], [IDL.Vec(CabAvailability)], ['query']),
    'getCabTypes' : IDL.Func([], [IDL.Vec(CabType)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyActingDriverRequests' : IDL.Func(
        [],
        [IDL.Vec(ActingDriverRequest)],
        ['query'],
      ),
    'getMyCabBookings' : IDL.Func([], [IDL.Vec(CabBooking)], ['query']),
    'getMyHotelBookings' : IDL.Func([], [IDL.Vec(HotelBooking)], ['query']),
    'getMyInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getMySalesOrders' : IDL.Func([], [IDL.Vec(SalesOrder)], ['query']),
    'getRoomAvailability' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DateRange)],
        ['query'],
      ),
    'getRoomTypes' : IDL.Func([], [IDL.Vec(RoomType)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestActingDriver' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCabAvailability' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'submitPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
    'updateActingDriverRequestStatus' : IDL.Func(
        [IDL.Text, BookingStatus],
        [],
        [],
      ),
    'updateCabBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
    'updateCallerSalesOrderDate' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'updateHotelBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
    'updateInquiryStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'new' : IDL.Null,
            'closed' : IDL.Null,
            'reviewed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updatePaymentStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'new' : IDL.Null,
            'verified' : IDL.Null,
            'rejected' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateSalesOrderStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };