/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CabBooking {
    status: BookingStatus;
    bookingId: string;
    dropoffLocation: string;
    cabType: string;
    bookingDate: bigint;
    guest: Principal;
    pickupTime: bigint;
    totalPrice: bigint;
    pickupLocation: string;
}
export interface HotelBooking {
    status: BookingStatus;
    depositAmount: bigint;
    bookingId: string;
    remainingAmount: bigint;
    checkInDate: bigint;
    bookingDate: bigint;
    guest: Principal;
    paymentPlan: PaymentPlan;
    checkOutDate: bigint;
    totalPrice: bigint;
    roomType: string;
    depositPercentage: bigint;
}
export interface PaymentRecord {
    status: Variant_new_verified_rejected;
    customer: Principal;
    note: string;
    reference: string;
    paymentId: string;
    timestamp: bigint;
    amount: bigint;
}
export interface SalesOrder {
    status: BookingStatus;
    deliveryAddress: string;
    remainingAmount: bigint;
    customer: Principal;
    orderDate: bigint;
    email: string;
    orderId: string;
    upfrontAmount: bigint;
    paymentPlan: PaymentPlan;
    contactNumber: string;
    products: Array<Product>;
    totalPrice: bigint;
}
export interface CabAvailability {
    availableCount: bigint;
    cabType: string;
}
export interface RoomType {
    features: Array<string>;
    imageUrls: Array<string>;
    pricePerNight: bigint;
    name: string;
    offerPrice: bigint;
}
export interface CabType {
    name: string;
    pricePerTrip: bigint;
    imageUrl: string;
    offerPrice: bigint;
    capacity: bigint;
}
export interface DateRange {
    checkIn: bigint;
    checkOut: bigint;
}
export interface ActingDriverRequest {
    status: BookingStatus;
    serviceDate: bigint;
    vehicleType: string;
    requestId: string;
    serviceDetails: string;
    bookingDate: bigint;
    guest: Principal;
}
export interface Inquiry {
    status: Variant_new_closed_reviewed;
    contactInfo: string;
    customer: Principal;
    message: string;
    timestamp: bigint;
    inquiryId: string;
}
export interface Product {
    imageUrls: Array<string>;
    name: string;
    description: string;
    productId: string;
    offerPrice: bigint;
    category: string;
    price: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum PaymentPlan {
    cod = "cod",
    partialUpfront = "partialUpfront",
    depositRequired = "depositRequired",
    fullUpfront = "fullUpfront"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_new_closed_reviewed {
    new_ = "new",
    closed = "closed",
    reviewed = "reviewed"
}
export enum Variant_new_verified_rejected {
    new_ = "new",
    verified = "verified",
    rejected = "rejected"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addRoomAvailability(roomType: string, dateRanges: Array<DateRange>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookCab(cabType: string, pickupLocation: string, dropoffLocation: string, pickupTime: bigint): Promise<string>;
    bookHotel(roomType: string, checkInDate: bigint, checkOutDate: bigint): Promise<string>;
    cancelCallerSalesOrder(orderId: string): Promise<void>;
    createSalesOrder(products: Array<Product>, deliveryAddress: string, contactNumber: string, email: string, totalPrice: bigint, paymentPlan: PaymentPlan): Promise<string>;
    getAllActingDriverRequests(): Promise<Array<ActingDriverRequest>>;
    getAllCabBookings(): Promise<Array<CabBooking>>;
    getAllHotelBookings(): Promise<Array<HotelBooking>>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getAllPayments(): Promise<Array<PaymentRecord>>;
    getAllRoomAvailability(): Promise<Array<[string, Array<DateRange>]>>;
    getAllSalesOrders(): Promise<Array<SalesOrder>>;
    getCabAvailability(): Promise<Array<CabAvailability>>;
    getCabTypes(): Promise<Array<CabType>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyActingDriverRequests(): Promise<Array<ActingDriverRequest>>;
    getMyCabBookings(): Promise<Array<CabBooking>>;
    getMyHotelBookings(): Promise<Array<HotelBooking>>;
    getMyInquiries(): Promise<Array<Inquiry>>;
    getMyPayments(): Promise<Array<PaymentRecord>>;
    getMySalesOrders(): Promise<Array<SalesOrder>>;
    getRoomAvailability(roomType: string): Promise<Array<DateRange>>;
    getRoomTypes(): Promise<Array<RoomType>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    requestActingDriver(vehicleType: string, serviceDetails: string, serviceDate: bigint): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setCabAvailability(cabType: string, availableCount: bigint): Promise<void>;
    submitInquiry(message: string, contactInfo: string): Promise<string>;
    submitPayment(reference: string, note: string, amount: bigint): Promise<string>;
    updateActingDriverRequestStatus(requestId: string, status: BookingStatus): Promise<void>;
    updateAdminCredentials(username: string, password: string): Promise<void>;
    updateCabBookingStatus(bookingId: string, status: BookingStatus): Promise<void>;
    updateCallerSalesOrderDate(orderId: string, newDate: bigint): Promise<void>;
    updateHotelBookingStatus(bookingId: string, status: BookingStatus): Promise<void>;
    updateInquiryStatus(inquiryId: string, status: Variant_new_closed_reviewed): Promise<void>;
    updatePaymentStatus(paymentId: string, status: Variant_new_verified_rejected): Promise<void>;
    updateSalesOrderStatus(orderId: string, status: BookingStatus): Promise<void>;
    verifyAdminCredentials(username: string, password: string): Promise<boolean>;
}
import type { ActingDriverRequest as _ActingDriverRequest, BookingStatus as _BookingStatus, CabBooking as _CabBooking, HotelBooking as _HotelBooking, Inquiry as _Inquiry, PaymentPlan as _PaymentPlan, PaymentRecord as _PaymentRecord, Product as _Product, SalesOrder as _SalesOrder, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addRoomAvailability(arg0: string, arg1: Array<DateRange>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoomAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoomAvailability(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookCab(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.bookCab(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookCab(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async bookHotel(arg0: string, arg1: bigint, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.bookHotel(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookHotel(arg0, arg1, arg2);
            return result;
        }
    }
    async cancelCallerSalesOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelCallerSalesOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelCallerSalesOrder(arg0);
            return result;
        }
    }
    async createSalesOrder(arg0: Array<Product>, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: PaymentPlan): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSalesOrder(arg0, arg1, arg2, arg3, arg4, to_candid_PaymentPlan_n3(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSalesOrder(arg0, arg1, arg2, arg3, arg4, to_candid_PaymentPlan_n3(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async getAllActingDriverRequests(): Promise<Array<ActingDriverRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActingDriverRequests();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActingDriverRequests();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCabBookings(): Promise<Array<CabBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCabBookings();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCabBookings();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHotelBookings(): Promise<Array<HotelBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHotelBookings();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHotelBookings();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPayments(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRoomAvailability(): Promise<Array<[string, Array<DateRange>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRoomAvailability();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRoomAvailability();
            return result;
        }
    }
    async getAllSalesOrders(): Promise<Array<SalesOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSalesOrders();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSalesOrders();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCabAvailability(): Promise<Array<CabAvailability>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCabAvailability();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCabAvailability();
            return result;
        }
    }
    async getCabTypes(): Promise<Array<CabType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCabTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCabTypes();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyActingDriverRequests(): Promise<Array<ActingDriverRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyActingDriverRequests();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyActingDriverRequests();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCabBookings(): Promise<Array<CabBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCabBookings();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCabBookings();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyHotelBookings(): Promise<Array<HotelBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyHotelBookings();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyHotelBookings();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInquiries();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInquiries();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPayments(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPayments();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPayments();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySalesOrders(): Promise<Array<SalesOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySalesOrders();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySalesOrders();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomAvailability(arg0: string): Promise<Array<DateRange>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomAvailability(arg0);
            return result;
        }
    }
    async getRoomTypes(): Promise<Array<RoomType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomTypes();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async requestActingDriver(arg0: string, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestActingDriver(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestActingDriver(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setCabAvailability(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCabAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCabAvailability(arg0, arg1);
            return result;
        }
    }
    async submitInquiry(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1);
            return result;
        }
    }
    async submitPayment(arg0: string, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async updateActingDriverRequestStatus(arg0: string, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActingDriverRequestStatus(arg0, to_candid_BookingStatus_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActingDriverRequestStatus(arg0, to_candid_BookingStatus_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateAdminCredentials(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminCredentials(arg0, arg1);
            return result;
        }
    }
    async updateCabBookingStatus(arg0: string, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCabBookingStatus(arg0, to_candid_BookingStatus_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCabBookingStatus(arg0, to_candid_BookingStatus_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCallerSalesOrderDate(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallerSalesOrderDate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallerSalesOrderDate(arg0, arg1);
            return result;
        }
    }
    async updateHotelBookingStatus(arg0: string, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHotelBookingStatus(arg0, to_candid_BookingStatus_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHotelBookingStatus(arg0, to_candid_BookingStatus_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateInquiryStatus(arg0: string, arg1: Variant_new_closed_reviewed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInquiryStatus(arg0, to_candid_variant_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInquiryStatus(arg0, to_candid_variant_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePaymentStatus(arg0: string, arg1: Variant_new_verified_rejected): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_variant_n35(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_variant_n35(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSalesOrderStatus(arg0: string, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSalesOrderStatus(arg0, to_candid_BookingStatus_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSalesOrderStatus(arg0, to_candid_BookingStatus_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyAdminCredentials(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminCredentials(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ActingDriverRequest_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActingDriverRequest): ActingDriverRequest {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_CabBooking_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CabBooking): CabBooking {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_HotelBooking_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HotelBooking): HotelBooking {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Inquiry_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentPlan_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentPlan): PaymentPlan {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRecord_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecord): PaymentRecord {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_SalesOrder_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesOrder): SalesOrder {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _BookingStatus;
    bookingId: string;
    dropoffLocation: string;
    cabType: string;
    bookingDate: bigint;
    guest: Principal;
    pickupTime: bigint;
    totalPrice: bigint;
    pickupLocation: string;
}): {
    status: BookingStatus;
    bookingId: string;
    dropoffLocation: string;
    cabType: string;
    bookingDate: bigint;
    guest: Principal;
    pickupTime: bigint;
    totalPrice: bigint;
    pickupLocation: string;
} {
    return {
        status: from_candid_BookingStatus_n8(_uploadFile, _downloadFile, value.status),
        bookingId: value.bookingId,
        dropoffLocation: value.dropoffLocation,
        cabType: value.cabType,
        bookingDate: value.bookingDate,
        guest: value.guest,
        pickupTime: value.pickupTime,
        totalPrice: value.totalPrice,
        pickupLocation: value.pickupLocation
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _BookingStatus;
    depositAmount: bigint;
    bookingId: string;
    remainingAmount: bigint;
    checkInDate: bigint;
    bookingDate: bigint;
    guest: Principal;
    paymentPlan: _PaymentPlan;
    checkOutDate: bigint;
    totalPrice: bigint;
    roomType: string;
    depositPercentage: bigint;
}): {
    status: BookingStatus;
    depositAmount: bigint;
    bookingId: string;
    remainingAmount: bigint;
    checkInDate: bigint;
    bookingDate: bigint;
    guest: Principal;
    paymentPlan: PaymentPlan;
    checkOutDate: bigint;
    totalPrice: bigint;
    roomType: string;
    depositPercentage: bigint;
} {
    return {
        status: from_candid_BookingStatus_n8(_uploadFile, _downloadFile, value.status),
        depositAmount: value.depositAmount,
        bookingId: value.bookingId,
        remainingAmount: value.remainingAmount,
        checkInDate: value.checkInDate,
        bookingDate: value.bookingDate,
        guest: value.guest,
        paymentPlan: from_candid_PaymentPlan_n16(_uploadFile, _downloadFile, value.paymentPlan),
        checkOutDate: value.checkOutDate,
        totalPrice: value.totalPrice,
        roomType: value.roomType,
        depositPercentage: value.depositPercentage
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        new: null;
    } | {
        closed: null;
    } | {
        reviewed: null;
    };
    contactInfo: string;
    customer: Principal;
    message: string;
    timestamp: bigint;
    inquiryId: string;
}): {
    status: Variant_new_closed_reviewed;
    contactInfo: string;
    customer: Principal;
    message: string;
    timestamp: bigint;
    inquiryId: string;
} {
    return {
        status: from_candid_variant_n21(_uploadFile, _downloadFile, value.status),
        contactInfo: value.contactInfo,
        customer: value.customer,
        message: value.message,
        timestamp: value.timestamp,
        inquiryId: value.inquiryId
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        new: null;
    } | {
        verified: null;
    } | {
        rejected: null;
    };
    customer: Principal;
    note: string;
    reference: string;
    paymentId: string;
    timestamp: bigint;
    amount: bigint;
}): {
    status: Variant_new_verified_rejected;
    customer: Principal;
    note: string;
    reference: string;
    paymentId: string;
    timestamp: bigint;
    amount: bigint;
} {
    return {
        status: from_candid_variant_n25(_uploadFile, _downloadFile, value.status),
        customer: value.customer,
        note: value.note,
        reference: value.reference,
        paymentId: value.paymentId,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _BookingStatus;
    deliveryAddress: string;
    remainingAmount: bigint;
    customer: Principal;
    orderDate: bigint;
    email: string;
    orderId: string;
    upfrontAmount: bigint;
    paymentPlan: _PaymentPlan;
    contactNumber: string;
    products: Array<_Product>;
    totalPrice: bigint;
}): {
    status: BookingStatus;
    deliveryAddress: string;
    remainingAmount: bigint;
    customer: Principal;
    orderDate: bigint;
    email: string;
    orderId: string;
    upfrontAmount: bigint;
    paymentPlan: PaymentPlan;
    contactNumber: string;
    products: Array<Product>;
    totalPrice: bigint;
} {
    return {
        status: from_candid_BookingStatus_n8(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        remainingAmount: value.remainingAmount,
        customer: value.customer,
        orderDate: value.orderDate,
        email: value.email,
        orderId: value.orderId,
        upfrontAmount: value.upfrontAmount,
        paymentPlan: from_candid_PaymentPlan_n16(_uploadFile, _downloadFile, value.paymentPlan),
        contactNumber: value.contactNumber,
        products: value.products,
        totalPrice: value.totalPrice
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _BookingStatus;
    serviceDate: bigint;
    vehicleType: string;
    requestId: string;
    serviceDetails: string;
    bookingDate: bigint;
    guest: Principal;
}): {
    status: BookingStatus;
    serviceDate: bigint;
    vehicleType: string;
    requestId: string;
    serviceDetails: string;
    bookingDate: bigint;
    guest: Principal;
} {
    return {
        status: from_candid_BookingStatus_n8(_uploadFile, _downloadFile, value.status),
        serviceDate: value.serviceDate,
        vehicleType: value.vehicleType,
        requestId: value.requestId,
        serviceDetails: value.serviceDetails,
        bookingDate: value.bookingDate,
        guest: value.guest
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cod: null;
} | {
    partialUpfront: null;
} | {
    depositRequired: null;
} | {
    fullUpfront: null;
}): PaymentPlan {
    return "cod" in value ? PaymentPlan.cod : "partialUpfront" in value ? PaymentPlan.partialUpfront : "depositRequired" in value ? PaymentPlan.depositRequired : "fullUpfront" in value ? PaymentPlan.fullUpfront : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    closed: null;
} | {
    reviewed: null;
}): Variant_new_closed_reviewed {
    return "new" in value ? Variant_new_closed_reviewed.new : "closed" in value ? Variant_new_closed_reviewed.closed : "reviewed" in value ? Variant_new_closed_reviewed.reviewed : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    verified: null;
} | {
    rejected: null;
}): Variant_new_verified_rejected {
    return "new" in value ? Variant_new_verified_rejected.new : "verified" in value ? Variant_new_verified_rejected.verified : "rejected" in value ? Variant_new_verified_rejected.rejected : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CabBooking>): Array<CabBooking> {
    return value.map((x)=>from_candid_CabBooking_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HotelBooking>): Array<HotelBooking> {
    return value.map((x)=>from_candid_HotelBooking_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRecord>): Array<PaymentRecord> {
    return value.map((x)=>from_candid_PaymentRecord_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalesOrder>): Array<SalesOrder> {
    return value.map((x)=>from_candid_SalesOrder_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActingDriverRequest>): Array<ActingDriverRequest> {
    return value.map((x)=>from_candid_ActingDriverRequest_n6(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentPlan_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentPlan): _PaymentPlan {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_new_closed_reviewed): {
    new: null;
} | {
    closed: null;
} | {
    reviewed: null;
} {
    return value == Variant_new_closed_reviewed.new ? {
        new_: null
    } : value == Variant_new_closed_reviewed.closed ? {
        closed: null
    } : value == Variant_new_closed_reviewed.reviewed ? {
        reviewed: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_new_verified_rejected): {
    new: null;
} | {
    verified: null;
} | {
    rejected: null;
} {
    return value == Variant_new_verified_rejected.new ? {
        new_: null
    } : value == Variant_new_verified_rejected.verified ? {
        verified: null
    } : value == Variant_new_verified_rejected.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentPlan): {
    cod: null;
} | {
    partialUpfront: null;
} | {
    depositRequired: null;
} | {
    fullUpfront: null;
} {
    return value == PaymentPlan.cod ? {
        cod: null
    } : value == PaymentPlan.partialUpfront ? {
        partialUpfront: null
    } : value == PaymentPlan.depositRequired ? {
        depositRequired: null
    } : value == PaymentPlan.fullUpfront ? {
        fullUpfront: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
